### ISSUE TITLE
Rename width / height variables

### ISSUE THREAD

**Issue by skrew** [HTTP-RPC/Lima#3]
Thanks for this (very great) library.

Like this fork https://github.com/fletcheryang2014/Lima/commit/8fa2cb20259fd65f5c181846f1b5e1fd4e0d9f0f it would be necessary to rename `width` and `height` because these variables conflict with almost all UIKit (+ Extensions) librairies.

Thanks

**Comment by gk-brown** [comment]
This would be quite an extensive change. Any suggestion for what these properties should be called instead?

**Comment by skrew** [comment]
On my fork, i have prefixed thoses with LM, like `lmwidth` instead of `width`

**Comment by gk-brown** [comment]
That makes sense. Out of curiosity, what libraries are you using that conflict with the current names?

**Comment by skrew** [comment]
Humm not sure but i think SwifterSwift and almost all libs with UIKit extensions

**Comment by gk-brown** [comment]
I see - SwifterSwift uses it as a shortcut for getting and setting the view's frame width/height explicitly. That's not something you would typically do when working with auto layout, which is why Lima's `width` and `height` extensions just apply a constraint.

Arguably, these properties could be renamed `layoutWidth` and `layoutHeight`, but I think I still prefer the simplicity of `width` and `height` - especially since Lima isn't really intended to be used in conjunction with manual layout code.
